tasks:
  - init: |
      export HMR_HOST=`gp url 3000`
      ./install.sh
    command: |
      ./run.sh
ports:
  - port: 4000
    onOpen: open-browser
  - port: 30000
    onOpen: ignore

vscode:
  extensions:
    - svelte.svelte-vscode
