tasks:
  - name: Install
    init: |
      sudo apt-get update
      sudo apt-get install -y coturn libgl1-mesa-dev xvfb
      ./install.sh
  - command: echo Done installing! Now press CTRL + SHIFT + B
ports:
  - port: 4000
    onOpen: notify
  - port: 30000
    onOpen: ignore

vscode:
  extensions:
    - svelte.svelte-vscode
    - ms-python.python
