tasks:
  - name: Install
    init: ./install.sh
  - command: echo Done installing! Now press CTRL + SHIFT + B
image:
  file: .gitpod.Dockerfile
ports:
  - port: 4000
    onOpen: notify
  - port: 30000
    onOpen: ignore

vscode:
  extensions:
    - svelte.svelte-vscode
    - ms-python.python
