tasks:
  - name: Install
    init: ./scripts/install.sh

ports:
  - port: 4000
    onOpen: notify
  - port: 30000
    onOpen: ignore

vscode:
  extensions:
    - svelte.svelte-vscode
    - ms-python.python
