services:
  robot:
    # we have a custom container that installes some video dependencies
    build: .
    container_name: dst-robot-robot
    volumes:
      - ./:/app
      - /app/node_modules/
      - /app/.pnpm-store
      - /app/apps/video/resources
      - /app/apps/video/config
    ports:
      - 9000:9000
      - 8889:8889
      - 8189:8189
    working_dir: /app
    command: sh -c "pnpm install && pnpm run robot:mock"
  web:
    image: node:21-alpine3.17
    container_name: dst-robot-web
    volumes:
      - ./:/app
      - /app/web/.svelte-kit
      - /app/.pnpm-store
      - /app/apps/video/resources
      - /app/apps/video/config
    ports:
      - 3000:3000
    working_dir: /app
    command: sh -c "npm i -g pnpm && pnpm install && pnpm run dev"
