services:
  web:
    build: .
    container_name: dst-robot
    volumes:
      - ./:/app
      - /app/node_modules/
      - /app/.pnpm-store
      - /app/apps/video/resources
      - /app/apps/video/config
    working_dir: /app
    command: sh -c "pnpm install && pnpm run robot:mock"
