name: Node.js CI

on:
  - push
  - pull_request

permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  cache-and-install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 9.1.1
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Generate .svelte-kit folder
        run: cd apps/web && pnpm run generate

      - name: Build necessary packages
        run: pnpm run build

      - name: Run tests
        run: pnpm run test

      - name: Check types
        run: pnpm run check

      - name: Copy env
        run: cp .env.example .env

      - name: Build static page
        working-directory: apps/web
        run: pnpm run build:static

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'apps/web/build'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
